baseURL = ""
languageCode = "en-us"
title = "Amoro"
theme = "amoro-theme"
sectionPagesMenu = "main"

[params]
  siteType = "landing-page"
  search = true
  description = "Management system for Lakehouse"
  docsBaseURL = ""
  githuburl = "https://github.com/apache/incubator-amoro"

[[params.social]]
  title = "Github"
  icon = "github-fill"
  url = "https://github.com/apache/incubator-amoro"
[[params.social]]
  title = "Issue Tracking"
  icon = "slack-square-fill"
  url = "https://github.com/apache/incubator-amoro/issues"
[[params.social]]
  title = "Wechat"
  icon = "wechat-fill"
  url = "javascript:void();"

[[params.features]]
  title = "Self-optimizing"
  desc = "Continuously optimizing tables, including compacting small files, change files, regularly delete expired files to keep high query performance and reducing storage costs."
  icon = "Self-managed"
[[params.features]]
  title = "Multiple Formats"
  desc = "Support different table formats such as Iceberg, Paimon, Mixed-Iceberg and Mixed-Hive to meet different scenario requirements and provide them with unified management capabilities."
  icon = "Multiple-Formats"
[[params.features]]
  title = "Catalog Service"
  desc = "Provide an unified catalog service for all computing engines, which can also used with existing metadata store service such as Hive Metastore and AWS Glue."
  icon = "Catalog-Service"
[[params.features]]
  title = "Rich Plugins"
  desc = "Provide various plugins to integrate with other systems, like continuously optimizing with Flink and data analysis with Spark and Kyuubi."
  icon = "Rich-Plugins"
[[params.features]]
  title = "Management Tools"
  desc = "Provide a variety of management tools, including WEB UI and standard SQL command line, to help you get started faster and integrate with other systems more easily."
  icon = "Management-tools"
[[params.features]]
  title = "Infrastructure Independent"
  desc = "Can be easily deployed and used in private environments, cloud environments, hybrid cloud environments, and multi-cloud environments."
  icon = "Infrastructure-Idependent"

[outputFormats.SearchIndex]
baseName = "landingpagesearch"
mediaType = "application/json"

[outputs]
home = [ "HTML", "RSS", "SearchIndex" ]

[menu]

  topnav = [
    { name = "Quickstart", weight = 100 },
    { name = "Setup", parent = "Quickstart", url = "/quickstart-setup/", weight = 101 },
    { name = "Quick Demo", parent = "Quickstart", url = "/quick-demo/", weight = 102 },
    { name = "Docs", weight = 200 },
    { name = "latest", parent = "Docs", url = "/docs/lastest/", weight = 201 },
    { name = "0.6.1", parent = "Docs", url = "/docs/0.6.1/", weight = 202 },
    { name = "Benchmark", weight = 300 },
    { name = "Benchmark Report", parent = "Benchmark", url = "/benchmark-report/", weight = 301 },
    { name = "Benchmark Guide", parent = "Benchmark", url = "/benchmark-guide/", weight = 302 },
    { name = "Download", url = "/download/", weight = 400 },
    { name = "Roadmap", url = "/roadmap/", weight = 500 },
    { name = "Community", weight = 600 },
    { name = "Join Community", parent = "Community", url = "/join-community/", weight = 601 },
    { name = "How to contribute", parent = "Community", url = "/how-to-contribute/", weight = 602 },
  ]

[markup.goldmark.renderer]
unsafe= true
